services:
  api:
    build: .
    image: api_image
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST=qdrant

  ingest:
    image: api_image
    command: python -m nasa_hackathon.ingest
    #profiles: ["ingest"]
    env_file:
      - .env
    environment:
      - HOST=qdrant
    depends_on:
      - api

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # Qdrant API port exposed to localhost
    volumes:
      - qdrant_storage:/qdrant/storage

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - neo4j_storage:/data
      - neo4j_storage:/logs
      - neo4j_storage:/import
      - neo4j_storage:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # BOLT
    restart: unless-stopped


volumes:
  qdrant_storage:
  neo4j_storage:
